version: "{build}"

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn

cache:
  - '%LOCALAPPDATA%/Yarn'

test_script:
  - node --version
  - npm --version
  - npm run flow
  - npm test

# Don't actually build.
build: off
